package org.kimwanyi.sacco.enums;

public enum AuditAction {
    LOGIN,LOGOUT,CREATE,UPDATE,DELETE,DEPOSIT,WITHDRAW,
    LOAN_APPLICATION,LOAN_APPROVAL,LOAN_REJECTION,PAYMENT,
    PASSWORD_CHANGE,ACCOUNT_LOCK
}
