package org.kimwanyi.sacco.enums;

public enum AuditAction {
    LOGIN,LOGOUT,CREATE_USER,UPDATE_USER,DEACTIVATE_USER,DEPOSIT,WITHDRAW,
    LOAN_APPLICATION,LOAN_APPROVAL,LOAN_REJECTION,PAYMENT,
    CHANGE_PASSWORD,ACCOUNT_LOCK,LOGIN_SUCCESS,LOGIN_FAILED,
    ASSIGN_ROLE,CREATE_MEMBER,CREATE_LOAN,APPROVE_LOAN,REJECT_LOAN,DEACTIVATE_MEMBER,
    LOAN_DISBURSEMENT,LOAN_REPAYMENT
}
